dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: jacobrickman-github
    token:
      secure: 7547812ea6854b4dd4124d048d26cfc625fd049a
script:
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
