dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "your_organization_key"
    token:
      secure: "your_token_encrypted_with_travis_encrypt_tool"
script:
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
